name: TEST_MACOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        echo -n "CPU型号:    " 
        sysctl -n machdep.cpu.brand_string
        echo -n "CPU核心数:  " 
        sysctl -n machdep.cpu.core_count
        echo -n "CPU线程数:  "
        sysctl -n machdep.cpu.thread_count
        echo "其它信息："
        system_profiler SPDisplaysDataType SPMemoryDataType SPStorageDataType | grep 'Graphics/Displays:\|Chipset Model:\|VRAM (Total):\|Resolution:\|Memory Slots:\|Size:\|Speed:\|Storage:\|Media Name:\|Medium Type:'
        mvn -v
