
name: CI_Deploy_SS_Docs

on:
  push:
  schedule:
  - cron: '0/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: '0.70.0'
        extended: true

    - name: Run a multi-line script
      run: |
        echo start to deploy ss doc...
        sh build-ss.sh
